### ISSUE TITLE
[Feat] 갤러리 뷰와 디테일 뷰 연결

### ISSUE THREAD

**Issue by eemdeeks** [DeveloperAcademy-POSTECH/MacC-Team10-OFO#20]
## 💡 Issue

갤러리 뷰와 디테일 뷰 연결 기능 구현

## 📝 Todo
- [x] 네비게이션을 통해서 연결
- [x] 모델 이용해서 목데이터 만들기
- [x] 목데이터로 갤러리 뷰 이미지 보여주기
- [x] 목 데이터 뒤딴(디테일뷰)으로 전달하기
- [x] 이미지 변경시 갤러리 뷰 전달
