### ISSUE TITLE
[Feat] 인증 샷 삽입/수정/삭제 기능 구현

### ISSUE THREAD

**Issue by eemdeeks** [DeveloperAcademy-POSTECH/MacC-Team10-OFO#5]
## 💡 Issue
기록 별 세부 뷰에 들어가는 기능으로,
인증 샷🌄 필드에 사진 넣는 기능입니다!

## 📝 Todo
- [x] 인증 샷 버튼 클릭 시 액션 시트 띄우기
- [x] 인증 샷 버튼 클릭 분기 나눠주기
- [x] 앨범 들어가서 사진 선택하기
- [x] 사진 선택 후 인증샷 필드에 선택한 사진 보이기
- [x] 삭제 클릭 시 인증샷 필드 디폴트 사진으로 변경하기

## 🐜ETC
- [AppleDoc_actionSheet](https://developer.apple.com/documentation/swiftui/actionsheet)

**Comment by sozohoy** [comment]
- 이슈 네이밍을 기능에 포커스 해서 수정해봤습니다!

**Comment by sozohoy** [comment]
- 추가로 FEAT -> Feat으로 수정했어요 ㅎ.ㅎ

**Comment by eemdeeks** [comment]
좋아요!

**Comment by hhajime** [comment]
b8efa5d
앱킷에 해당하는 부분은 꼭 필요할까요? macOS 관련 코드 같아서요!

```
            #if canImport(AppKit)
                guard let nsImage = NSImage(data: data) else {
                    throw TransferError.importFailed
                }
                let image = Image(nsImage: nsImage)
                return ProfileImage(image: image)
            #elseif canImport(UIKit)
                guard let uiImage = UIImage(data: data) else {
                    throw TransferError.importFailed
                }
                let image = Image(uiImage: uiImage)
                return CertifyingImage(image: image)
```

**Comment by eemdeeks** [comment]
맞는 거 같아요! 
코드를 Apple Document에서 가져와서 진행하면서 이해하고 있는데, macOS부분이 아직 이해가 안돼서 혹시 몰라 가만히 뒀습니다!
pr올릴 때 수정해서 올릴게요 :]
